### ISSUE TITLE
Fix landing page for future Antelope docs

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/devrel#107]
http://docs.eosnetwork.com/

It currently reads:
- EOS Developer Documentation
- How EOS works; etc.

It should read:
- Antelope Developer (or Framework) Documentation
- How Leap works; etc.

Prereqs:
- This has to be done only after moving devdocs scripts from Antelope to ENF.

**Comment by nsjames** [comment]
This work was already completed in the redesign.
