### ISSUE TITLE
Twitter spaces panelist outreach

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#120]
We need backup topics for Twitter spaces when there are no hype waves to ride. 

AC:
- Create a list of 2*6 (2 spaces a week, 6 weeks) topics
- Output these as a spreadsheet in our drive (We will turn these into a public schedule in the future)

**Comment by JonaedIqbal** [comment]
Building this document. 
https://docs.google.com/spreadsheets/d/15kdET81FA7Wtn5D3D6mM5iaOCfSEyyKrjD6rhsixaLY/edit?usp=sharing

**Comment by nsjames** [comment]
We've put this initiative on indefinite hold for now, closing this out. 
Will re-open if this initiative gets picked up again.
