### ISSUE TITLE
Craft content creation course

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#124]
The content creation course syllabus / modules need to be refined to reach a quicker MVP

AC:
- Decide which modules are essential
- Outline the scripts 
- Record the videos

**Comment by JonaedIqbal** [comment]
Link to course https://docs.google.com/document/d/1M7zrM_RE03gBvOImG3HxOGVZyuKnwz_Zcd-opiTvW2U/edit?usp=sharing

**Comment by nsjames** [comment]
We've put this initiative on indefinite hold for now, closing this out. 
Will re-open if this initiative gets picked up again.
