### ISSUE TITLE
SPIKE - Create document with ecosystems/individuals to interview

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#128]
We need to identify people within various ecosystems to interview for DeCafe

AC:
- Create a list of people within the following ecosystems:
  - Web3 (defi, gamefi, exchanges, foundations, etc)
  - Web2
  - Gaming
  - DevRel (any ecosystem)
  - Output these as a spreadsheet in our drive

**Comment by JonaedIqbal** [comment]
Link to document (still updating) -https://docs.google.com/spreadsheets/d/1P9_rZqhUghcP8tp0QMfPG5jUdzvlGf-c0ZObch48Fo0/edit?usp=sharing

**Comment by nsjames** [comment]
We've put this initiative on indefinite hold for now, closing this out. 
Will re-open if this initiative gets picked up again.
