### ISSUE TITLE
SPIKE - Gather information required for a node operator getting started

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#133]
Gather information to create a guide to help developers raise and connect an API node to the mainnet. 

This is **not** meant to explain:
- History solutions
- Block production

This **is** meant to explain:
- [x] Basic hardware requirements
- [x] How to install leap
- [x] How to setup a config.ini
- [x] How to setup peers
- [x] How to start/stop a node
- [x] What blocks.log is
- [x] What a snapshot is and how to replay from one
- [x] What to do if the blocks are "dirty"
- [x] How to set cors to `*` for dapp usage

AC:
- Find the simplest method for API node deployment
- Compile all the information required and dump it into a document to be used for the writing of the guide
- Create a ticket to write the guide linking to the required information

**Comment by lparisc** [comment]
This task is part of a larger effort within a node operator section (TBD).

Here, we'll focus on deploying a validator node for validation purposes.

**Comment by nsjames** [comment]
Please reference the "Getting started" section of this list: https://github.com/eosnetworkfoundation/devrel/issues/221

**Comment by lparisc** [comment]
> Compile all the information required and dump it into a document to be used for the writing of the guide
https://hackmd.io/@EOSNF/SyMfjCL43

> Create a ticket to write the guide linking to the required information
https://github.com/eosnetworkfoundation/devrel/issues/282
