### ISSUE TITLE
Using Hardhat with EOS EVM

### ISSUE THREAD

**Issue by VEG-Ginna** [eosnetworkfoundation/devrel#146]
Create documentation about how to use Hardhat with EOS EVM

AC:
- Define the config needed to use with EOS EVM
- Write simple guide (like truffle guide)
- Separate [truffle guide](https://staging-docs.eosnetwork.com/docs/latest/eos-evm/developer-guide/smart-contracts) into its own guide

**Comment by nsjames** [comment]
Rolled into https://github.com/eosnetworkfoundation/devrel/issues/209
