### ISSUE TITLE
Define DevRel Mission Statement

### ISSUE THREAD

**Issue by VEG-Ginna** [eosnetworkfoundation/devrel#15]
Develop a mission statement for the DevRel team.

Prerequisites:
- N/A

Definition of Done:
- A reviewed, approved mission statement for the ENF DevRel team

**Comment by VEG-Ginna** [comment]
Mission Statement created and out for review (Nathan, Luis, Ovi)
https://docs.google.com/document/d/1aXZD_IrqF283O6OIhhhwlUltVQbnCiYJYjZEGGLvIpg/edit#

**Comment by nsjames** [comment]
We've defined this as a much simpler shining light: "Empower EOS developer community"
