### ISSUE TITLE
Hide "Get Involved" from sidebar

### ISSUE THREAD

**Issue by VEG-Ginna** [eosnetworkfoundation/devrel#153]
Need time to revamp the Get Involved page, therefore we are removing it from the documentation for now.

AC:
- Get Involved page removed
- Create another ticket to rewrite Get Involved page

**Comment by lparisc** [comment]
- Created PR to remove Get Involved section (in Review)
- Created ticket #190 to rewrite Get Involved section.

**Comment by lparisc** [comment]
Staging doesn't show Get Involved section anymore, so closing as complete.
