### ISSUE TITLE
Create Dune Smart Contract Developer's written guide

### ISSUE THREAD

**Issue by VEG-Ginna** [eosnetworkfoundation/devrel#162]
AC:
- Windows, and Linux all need to have installation
- Define what part of DUNE need to be documented (look at readme)
  - Only document things which are related to our development needs
    - Start / stop chain 
    - Start boilerplate
    - Compile and deploy
    - Create account (#161) 
    - Run tests
    - Sending actions
    - Get table data
- Implement guide on `docs` 
- Create a new ticket for the video course of this written guide

**Comment by lparisc** [comment]
- [x] #185
- [ ] Create dune guide file with TOC headings below

TOC:
- [ ] Overview
- [ ] Installation
  - [ ] Linux (@iamveritas)
  - [ ] Windows
- [ ] Node setup
  - [ ] Set up EOS node(s)
  - [ ] Create wallets and keys
  - [ ] Create test accounts
- [ ] Smart Contract Development
  - [ ] First contract "Hello World" with write/read row (consider: singleton contract instead)
    - [ ] Compile contract
    - [ ] Deploy contract
- [ ] Smart Contract Testing
  - [ ] Send actions
  - [ ] Get table data
- [ ] Summary

**Comment by nsjames** [comment]
Small comments were posted in the telegram channel about merging the two contracts into one
