### ISSUE TITLE
Create resources written guide

### ISSUE THREAD

**Issue by VEG-Ginna** [eosnetworkfoundation/devrel#166]
AC:
- CPU&NET
  - PowerUp system
  - What CPU is and how it is calculated
  - What NET is and how it is calculated 
  - Dry run transaction endpoint (`send_transaction2`)
- RAM
  - Its uses
  - The market & how to buy (bytes vs token quantity)
  - Understanding multi_index overhead
    - Calculating the cost of a row based on the struct
    - Table & row overhead for metadata
    - Secondary indexes and their RAM overhead
- Create a new ticket for the video course of this written guide

**Comment by iamveritas** [comment]
in progress:

https://github.com/eosnetworkfoundation/docs/pull/43/files
https://github.com/eosnetworkfoundation/eos-system-contracts/pull/63/files

**Comment by iamveritas** [comment]
I moved it from review to in progress cause I want to create only one document out of all the content produced so far

**Comment by iamveritas** [comment]
This is the PR for the one single doc "resources guide":
https://github.com/eosnetworkfoundation/docs/pull/48

These two PRs are updating the existing docs we have around resources topic:
https://github.com/eosnetworkfoundation/docs/pull/43/files
https://github.com/eosnetworkfoundation/eos-system-contracts/pull/63/files

**Comment by iamveritas** [comment]
video course guide ticket created here
https://github.com/orgs/eosnetworkfoundation/projects/18/views/10?filterQuery=vertical%3ADocs+-status%3ADone&pane=issue&itemId=20607542
