### ISSUE TITLE
Create accounts written guide

### ISSUE THREAD

**Issue by VEG-Ginna** [eosnetworkfoundation/devrel#167]
AC:
- Define what an account is
- Name restrictions (a-z1-5), & name bids
- Very basic permissions
- Public/Private Keys
- Associated costs
- An account can hold a smart contract
- Creating an account with DUNE
- Talk about how accounts are what have ownership over digital assets
- Name bid system
- Figure out where to put this document (possibly nested in smart contracts)
- Create a new ticket for the video course of this written guide

**Comment by nsjames** [comment]
Missing associated costs & ownership of resources
