### ISSUE TITLE
Create Smart Contracts Basics written guide

### ISSUE THREAD

**Issue by VEG-Ginna** [eosnetworkfoundation/devrel#168]
AC:
- [x] Write the content
  - examples rewritten using Dune
  - HPP & CPP structure & basics
  - Actions
  - EOS/Antelope Types
  - Structs 
  - Primary and Secondary indexes
  - multi_indexes
      - get/set/update/delete
      - code/scope/table
  - Singleton
     - get/set/update/delete
     - code/scope/table
  - Authorization (require_auth)
  - Assertions
  - Events
      - on_notify
      - require_recipient
  - Inline actions
       - Preparation
       - Execution
       - Order of execution
- [x] Create a new ticket for the video course of this written guide
- [x] Clean up
  - Remove the following [guides](https://github.com/eosnetworkfoundation/docs/tree/staging/docs/20_smart-contracts/30_tutorials): 
  - Hello world Contract
  - Data persistence
  - Secondary indices
  - Adding inline actions
  - Inline actions to external contracts
  - Payable actions

**Comment by iamveritas** [comment]
Created a new ticket for the video course of this written guide

https://github.com/orgs/eosnetworkfoundation/projects/18/views/10?filterQuery=vertical%3ADocs+-status%3ADone&pane=issue&itemId=21897293
