### ISSUE TITLE
SPIKE - Define the scope for Technical Hackathon Workshop

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#17]
We want to make sure that we don't go too technical. 

Need to know:
- What accounts and permissions are
- Transaction Lifecycle
- Tables and Data
- What EOS's TPS is
- What they can and can't do
- What RAM is
- What resources are (NET/CPU)
- What smart contract languages are available

References: 
- Overview: https://docs.google.com/document/d/1BdYE6TQWzXfcopI-Loh4lA19k4nsGRF9570bl-VVGLg/edit#heading=h.8lpx20u5ic79
- Shared drive: https://drive.google.com/drive/u/1/folders/1F244ZLrEsoUlXG2PEumsjjPdULf_YYdB

AC:
- Define what parts of EOS / Antelope need to be discussed
- Create a syllabus with each category defines
- Create a list of slides which need to be created
- Create "tasks" to create the slides and in-depth syllabus

----

Categories for winning: 

DeFi: Decentralized financial instruments or tools that do not rely on a 'trusted third party' or intermediaries, and leverage smart contracts on a public blockchain.

Gov3: Decentralized governance services or tools that empower individuals/communities to meaningfully interact and collaborate when establishing consensus on rules and mechanisms by which people distribute power and control.

GameFi: Play-to-earn blockchain based games that provide mechanics to yield economic incentive for players to play or interact with the game.

Social Good: Decentralized applications, services, or tools that leverage a public blockchain while improving the quality of life for the most people in the biggest way.

Web3: Decentralized applications, services, or tools that explicitly disintermediate an interaction and value-exchange to therefore increase the maximum potential value remitted to or saved by an end user/customer.

**Comment by ericpassmore** [comment]
- https://cc32d9.gitbook.io/antelope-smart-contract-developers-handbook/
- https://eos.io/news/eosio-history-tools/
- https://developers.eos.io/manuals/eosio.cdt/latest/best-practices/index

**Comment by ericpassmore** [comment]
completed a writeup in google docs.

**Comment by ericpassmore** [comment]
# Why Antelope
## What does this mean for me?
### Scale and Speed
### Smart Contracts
### Cross Cutting Power of Permissions
- Unlock new level3 in a game, for gamers who beat level2
- Open up events to VIP members.
- Change the moderator of a social network every week
### Persisting Data
- User Profiles Stored with Antelope.
- Storing telemetry from IoT devices. 
- Track state of play.
- Track multiple metrics for granting tokens.
- Suspend a license not a business.
## Recap
## Advanced Examples
- Lambda Architecture/ Data Warehousing
- Order Books
