### ISSUE TITLE
Create a Creating a Token written guide

### ISSUE THREAD

**Issue by VEG-Ginna** [eosnetworkfoundation/devrel#172]
AC:
- [x] What is a token?
- [x] Promote usage of standard [token contract](https://github.com/eosnetworkfoundation/eos-system-contracts/tree/main/contracts/eosio.token)
- [x] Demonstrate:
  - [x] issue
  - [x] burn
  - [x] transfer
- [x] Create a new ticket for the video course of this written guide

**Comment by nsjames** [comment]
https://github.com/eosnetworkfoundation/docs/pull/101/files

**Comment by nsjames** [comment]
https://github.com/eosnetworkfoundation/devrel/issues/231
