### ISSUE TITLE
Rename all instance of Trust with EOS

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#177]
https://github.com/eosnetworkfoundation/evmdocs

AC:
- [x] Go through the EVM docs and replace the term "Trust" with "EOS" (Trust EVM to EOS EVM, Trust Network to EOS EVM Network, etc)
- [ ] Figure out what to do with domains, if we want to do it in this ticket
- [ ] Figure out socials and links, if we want to create another ticket

**Comment by iamveritas** [comment]
These are all the Trust occurrences that we need to address:

# URLs:

**Telegram of Developer Community**: [`https://t.me/TrustEVMDev`](https://t.me/TrustEVMDev)
* **Official Email**: trustevm@gmail.com
* **Twitter of EOS EVM**: [`https://twitter.com/trustevm`](https://twitter.com/trustevm)
* `New RPC URL`: https://api-testnet.trust.one/
* `Block Explorer URL (Optional)`: https://explorer-testnet.trust.one/
* Main RPC URL: [https://api-testnet.trust.one](https://api-testnet.trust.one)
* [Blockscout](https://explorer-testnet.trust.one/)
* EVM Token: [`https://faucet-testnet.trust.one/`](https://faucet-testnet.trust.one/)``
host: "api-testnet.trust.one",
https://explorer-testnet.trust.one/address/SMART_CONTRACT_ADDRESS/verify-via-flattened-code/new

# Repos (and the local TrustEVM dir/folder name resulted from pulling locally):

https://github.com/eosnetworkfoundation/TrustEVM/blob/main/docs/compilation_and_testing_guide.md

# branch name in the https://github.com/elmato/blockscout repo

git checkout trust

# Binaries (search their names in all docs):

- trustevm-node: silkworm node process that receive data from the main Antelope chain and convert to the EVM chain
- trustevm-rpc: silkworm rpc server that provide service for view actions and other read operations

# tool parameter/s

./trustevm-rpc --api-spec=eth,net --http-port=0.0.0.0:8881 --trust-evm-node=127.0.0.1:8080 --chaindata=./chain-data

# EVM genesis sample (json file):
        "extraData": "TrustEVM",

**Comment by iamveritas** [comment]
PR in review:
https://github.com/eosnetworkfoundation/docs/pull/59/files

**Comment by lparisc** [comment]
Added fixes/edits and merged.

**Comment by iamveritas** [comment]
we shall keep this open to track the changes that are still needed and listed here
https://github.com/eosnetworkfoundation/devrel/issues/177#issuecomment-1465288465
all those changes are not in dev rel team control.

**Comment by Joshua2Mars** [comment]
Areg and Matias are trying to create a new repo and cleanup the "trust" thing. ETA: next monday
