### ISSUE TITLE
SPIKE - Evaluate the EVM docs

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#178]
AC:
- Assess quality & correctness
- Assess completeness
- Assess developer journey
- Assess ease of understandability 
- Output tickets for improvements

**Comment by iamveritas** [comment]
Proposed Structure for EOS EVM content

EOS EVM (main entry on the left side menu, what follows are sub-items/sub-sections)

What is EOS EVM (TODO: brief one page introduction to EOS EMV)
Connect to EOS EVM Network (TODO: improved current page content)
	How to Connect Metamask (current page content)
Develop on EOS EVM (TODO: ToS for its sub-items)
	Getting Started (TO DO: curated current content from "Smart Contracts" page)
	Develop EOS EVM Smart Contract
		Develop with Remix (current page content)
		Develop with Truffle Suite (TO DO: improved current content from existing sub-page)
		Develop with Hardhat (TO DO: new page, similar to Truffle one)
	How to Verify a Smart Contract (current page content)
	Compatibility (TODO: Tos for its sub-items)
		EVM Compatibility (TODO: curated and improved current page content)
		JSON RPC Compatibility (TODO: curated and improved current page content)
	Architecture (TODO: current page content + what SMEs will provide in the future) 	Deploy Local Testnet with EVM Support (TODO: curated current page content)
Resources (TODO: curated current page content)

**Comment by nsjames** [comment]
```
EOS EVM (main entry on the left side menu, what follows are sub-items/sub-sections)

What is EOS EVM (TODO: brief one page introduction to EOS EMV)
Getting Started (TODO: ToS for its sub-items)
        Connect Metamask (current page content)
	Smart Contracts
		Develop with Remix (current page content)
		Develop with Truffle Suite (TO DO: improved current content from existing sub-page)
		Develop with Hardhat (TO DO: new page, similar to Truffle one)
		Verify a Smart Contract (current page content)
Compatibility (TODO: Tos for its sub-items)
	EVM Compatibility (TODO: curated and improved current page content)
	JSON RPC Compatibility (TODO: curated and improved current page content)
Architecture (TODO: current page content + what SMEs will provide in the future)
Resources (TODO: curated current page content)
```

**Comment by iamveritas** [comment]
tasks created based on this spike:
https://github.com/orgs/eosnetworkfoundation/projects/18/views/21?pane=issue&itemId=23515412
https://github.com/orgs/eosnetworkfoundation/projects/18/views/21?pane=issue&itemId=23515889
https://github.com/orgs/eosnetworkfoundation/projects/18/views/21?pane=issue&itemId=23516592
