### ISSUE TITLE
Merge EVM docs into docs

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#180]
We want to merge the https://github.com/eosnetworkfoundation/evmdocs into the docs github so that they are on the same documentation. 

This should be in an `EVM` sidebar item which is also on the navbar as one of the `Learn` options. 

AC:
- Reformat docs to our formats
- Merge in `EVM` docs into the sidebar
- Add `EVM` into the navbar under `Learn` (https://github.com/eosnetworkfoundation/docsgen/blob/master/config/docusaurus.config.js)
- Build for staging
- Build for production

**Comment by iamveritas** [comment]
PR
https://github.com/eosnetworkfoundation/docs/pull/49
