### ISSUE TITLE
Create index file for docsgen documentation

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/devrel#181]
The current docsgen [README](https://github.com/eosnetworkfoundation/docsgen/blob/main/README.md) file is bloated with information. This ticket will organize the content as follows:
- Create an `index.md` at https://github.com/eosnetworkfoundation/docsgen/tree/main/docs to organize the folder contents.
- Move content starting from https://github.com/eosnetworkfoundation/docsgen/blob/main/README.md#initialize-content-repository in the README file and use it as foundation building such an index.md file. Also consolidate https://github.com/eosnetworkfoundation/devrel/blob/1dd83db7ac04ff53404bdba4daf746ab3e4af9ce/Processes/Internal-Build-and-Release-Process.md into that index file.
- Make sure all files within the docs folder are accounted for (have an entry in the index file).
- Create a "generating content" quick guide on a separate doc file (content currently at https://github.com/eosnetworkfoundation/docsgen/blob/main/README.md#generating-content) and create two paragraphs on index that describe how to generate content using `clean_rebuild.sh` and `generate_documents.sh` scripts, respectively.
- After moving the content, replace heading [Initialize Content Repository](https://github.com/eosnetworkfoundation/docsgen/blob/main/README.md#initialize-content-repository) with "Documentation" then add a paragraph that links to the index file... "For information on how to generate content, updating site navigation, updating the UX, production setup, and testing, visit the \[documentation]\(index.md) section."

**Comment by VEG-Ginna** [comment]
Docsgen #181/PR90 - needs review
