### ISSUE TITLE
Rewrite Get Involved section in sidebar

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/devrel#190]
The Get-Involved section needs updated images for docs portal and the message repurposed for community contribution needs.

AC:
- new Get Involved section folder created
- index.md file with Get Involved content
- potentially add [previous reference](https://github.com/eosnetworkfoundation/docs/blob/a32bbe47003bd727e87b34252146e4ef76b45eb6/docs/10_overview/03_technical_features.md#see-also) to new Get Involved

**Comment by nsjames** [comment]
Closing this ticket as we no longer have this section, nor do I think we need it.
