### ISSUE TITLE
Remove Overview and other sections from Staging

### ISSUE THREAD

**Issue by VEG-Ginna** [eosnetworkfoundation/devrel#196]
For the docs, please remove: 

- Overview
- Smart contracts -> concepts
- Smart contracts -> guides
- Resources -> Testnets

Before pushing staging to prod. 

We can work on bringing some of that info back later but it's all either empty, marketing fluff, superseded, or pointing people outside of EOS.

**Comment by lparisc** [comment]
Child of #191

**Comment by lparisc** [comment]
Notes for reviewer:
- just visit the staging site and make sure there are no broken links within the docs. please report here if any. thx

**Comment by lparisc** [comment]
> DocsGen - Mandel Swift Readme file - link EOS RPC API is broken DocsGen - Dune - auto complete - URL at end of paragraph DocsGen - Leap - Install - "built" DocsGen - Tutorials - Docs - EOS Developers Documentation Site (404) DocsGen - Glossary - Docs - EOS Developers Documentation Site (404) DocsGen - Docs - Docs - EOS Developers Documentation Site (404)

This is the review from another ticket #181, whose PR was already merged, and for which you are the assignee, so others will review it for you, not yourself. The review of this ticket involves the following:
- Checking the pages from the sidebar menu here: http://staging-docs.eosnetwork.com/docs/latest/
- Make sure there are no broken links anywhere on the sidebar menu or the page contents.

**Comment by VEG-Ginna** [comment]
the following links are broken on the sidebar
Tic-Tac-Toe on EOS 
   - Getting Started for Node Operators
   - Installing EOS binaries
   - Install the CDT
   - Overview of the EOS blockchain
   - Get started with EOS Smart Contracts
   - Accounts and Permissions
   - Transactions Protocol
   - bootstrapping a blockchain for real world use
   - resigned

Let me know if you need anything else. Review finished.
