### ISSUE TITLE
EOS EVM Workshop

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#211]
Timeline: End of April, early May

Content:
- What is EVM
- Quickstart
- Basic smart contract
- Deploying to chain
- Using MetaMask

AC:
- Create webinar materials
- Set date for webinar & communicate to marcom

**Comment by iamveritas** [comment]
- What is EVM: 
   https://hackmd.io/@EOSNF/S1w35qEGn#EOS-EVM-v040-Release-Notes and 
   https://staging-docs.eosnetwork.com/docs/latest/eos-evm/what_is_eos_evm
- Quickstart 
   https://staging-docs.eosnetwork.com/docs/latest/eos-evm/getting_started/
- Basic smart contract 
   https://staging-docs.eosnetwork.com/docs/latest/eos-evm/getting_started/smart-contracts and 
   https://staging-docs.eosnetwork.com/docs/latest/smart-contracts/
- Deploying to chain 
   https://staging-docs.eosnetwork.com/docs/latest/eos-evm/getting_started/develop-with-remix
- Using MetaMask 
   https://staging-docs.eosnetwork.com/docs/latest/eos-evm/getting_started/connect-metamask
