### ISSUE TITLE
Add chinese locale to docs portal

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/devrel#213]

**Comment by lparisc** [comment]
4/17/23: meeting with SME today for guidance and tips on docusaurus i18n localization efforts

**Comment by nsjames** [comment]
Moved to fridge so we can architect a solution for this

**Comment by lparisc** [comment]
Asked suggestions/pointers from Automation team re: this effort. Potential options I could find so far:
- [Amazon Machine Translate](https://aws.amazon.com/translate/)
- [Google Cloud Translation](https://cloud.google.com/translate)
- Other 3rd party solutions:
  * mdpo: [site](https://mondeja.github.io/mdpo/latest/), [source](https://github.com/mondeja/mdpo) (open source)
  * GT4T: [site](https://gt4t.net/)
  * Translate-markdown: [source](https://github.com/rhysd/translate-markdown) - no good! (strips md, then web-xlates).

**Comment by kj4ezj** [comment]
> Asked suggestions/pointers from Automation team[...]

Closing the loop on this, I got @nsjames access to AWS Translate on 2023-05-15. This is outside my area of expertise so I do not have any specific recommendations for translation besides having native Mandarin Chinese (中文) speakers in the ENF review any computer translations. We do not want to publish documentation in 洋式中文 (the inverse of Chinglish).

Once your team has a translation workflow established, I would be happy to help automate that workflow.

**Comment by nsjames** [comment]
Moved to frozen, almost done but blocked by this: https://github.com/eosnetworkfoundation/devrel/issues/319

**Comment by nsjames** [comment]
"We do not want to publish documentation in 洋式中文 (the inverse of Chinglish)."

Just wanted to reply to this. We indeed **do** want to publish documentation with machine translations, regardless of how bad they are. This is the first step in an iterative process to getting a translation flow up and running. 

1. Machine translate
2. Human review
3. Build grammar lexicon for machine translator from reviews

When a document changes, it will then revert to 1, and require going through the process again. 

**We do not want to wait for the process to be fully implemented before releasing**.
