### ISSUE TITLE
Add web redirects for EVM getting started

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/devrel#218]
AC:
- rename the EVM `getting_started` folder to `getting-started` (replace '_' with '-').
- update the Apache config file for docs.eosnetwork.com to allow all web traffic within `getting_started` to be redirected to `getting-started`, that is:
  * any web links under:
https://docs.eosnetwork.com/docs/latest/eos-evm/getting_started/*
  * must be redirected to:
https://docs.eosnetwork.com/docs/latest/eos-evm/getting-started/*

**Comment by nsjames** [comment]
All links have been fixed to use hyphen, a hyphen check was added to CI, and some aliases were added for things that have been linked externally
