### ISSUE TITLE
Guide: Getting data from the chain

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#219]
We need a guide that documents the full functionality of getting table data from the chain

AC:
- Use POST requests to explain the actual structures
- Go through the full result schema
- Go through the POST data json
- Explain the "more" cursor and pagination
- Explain the timeout considerations
- Show how to use cleos to interact with tables

**Comment by stephenpdeos** [comment]
Will resolve https://github.com/AntelopeIO/leap/issues/608

**Comment by iamveritas** [comment]
PR in review: https://github.com/eosnetworkfoundation/docs/pull/131
