### ISSUE TITLE
Create tickets to review quality of documentation

### ISSUE THREAD

**Issue by VEG-Ginna** [eosnetworkfoundation/devrel#236]
Create initial tickets for documentation portal content

Documentation Portal content (to include sub-topics):

- Smart Contracts
- EOS EVM
- https://docs.eosnetwork.com/docs/latest/migration-guides/v1-history-alternatives
- https://docs.eosnetwork.com/docs/latest/glossary
- https://github.com/eosnetworkfoundation/docs/pulls (2 tickets which are in review can also have tickets created for them)
- 

AC:
- Create a set of GitHub tickets to review each documentation portal content for
- Likely to change large portions:
     - [ ]  2nd person voice
     - [ ]  comprehension (5th grade reading level)
     - [ ]  ability to machine translate
     - [ ] grammar (keep it light)
     - [ ] Make headers first-cap only
- Likely only smaller changes
     - [ ] spelling 
     - [ ] check `<head><title></title></head>` for uniqueness
- Add the checklist to each ticket
- For things with guide-wide changes, make a separate PR (like title/heading fixes)

**Comment by VEG-Ginna** [comment]
Tickets #250 - #274 created

**Comment by nsjames** [comment]
This is missing a few which were created during this iteration: 

https://github.com/eosnetworkfoundation/devrel/issues/247

https://github.com/eosnetworkfoundation/devrel/issues/243

https://github.com/eosnetworkfoundation/devrel/issues/173

https://github.com/eosnetworkfoundation/devrel/issues/172

https://github.com/eosnetworkfoundation/devrel/issues/249

After this move back to review on me please so I can slot them into the new tw roadmap and then we can close this out

**Comment by nsjames** [comment]
Each ticket should have the checkboxes (`- [ ]`)

**Comment by VEG-Ginna** [comment]
Fixed Checkboxes

Added Tkts 277 - 281 as requested (need to add links to published docs when they are published)
