### ISSUE TITLE
Add automation to production and staging deployments

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/devrel#237]
Automate the `docsgen` scripts further when deploying to production and staging

AC:
- Merge `docsgen` repo `staging` branch to `main`
- Add functionality to clone docsgen repo so that...
  * `main` branch is checked-out/pulled when deploying to production site
  * `staging` branch is checked-out/pulled when deploying to staging site
- Then invoke `clean_rebuild.sh` script as usual

**Comment by nsjames** [comment]
Docsgen was rewritten into https://github.com/eosnetworkfoundation/docs-ui 

Since we never had a ticket for it, I'll just close this one as done instead of discarded.
