### ISSUE TITLE
Documentation missing for action return values

### ISSUE THREAD

**Issue by jdheeter** [eosnetworkfoundation/devrel#240]
Activated on block 269183454 with the other v3.1 protocol features but not listed in official documentation when I searched for more information.

**Comment by nsjames** [comment]
Can see these here now: https://docs.eosnetwork.com/docs/latest/smart-contracts/advanced_concepts/action-types

**Comment by jdheeter** [comment]
> Can see these here now: https://docs.eosnetwork.com/docs/latest/smart-contracts/advanced_concepts/action-types

@nsjames the link is a 404 for me. I did a search of the docs "Action return value" and did not find the page.

**Comment by jdheeter** [comment]
I found the page here https://docs.eosnetwork.com/docs/latest/smart-contracts/advanced-concepts/action-types looks like _ instead of - in the link you posted. Reading the page now, It's not clear to me how to utilize the feature from a client so maybe it would be good to have a client example for this feature.
