### ISSUE TITLE
Document chain api endpoints not present currently in docs

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#248]
the current task is a continuation of this one:
https://github.com/orgs/eosnetworkfoundation/projects/18/views/21?pane=issue&itemId=23127963

there are 4 more which are not documented:

  /get_code_hash
  /get_producer_schedule
  /get_transaction_id
  /send_read_only_transaction
  /push_block

AC:
- Update chain API swagger files
- Include:
  - Input parameters
  - Output results
  - Brief description about what the route does

**Comment by iamveritas** [comment]
done
https://github.com/eosnetworkfoundation/docs-ui/pull/4
https://github.com/AntelopeIO/leap/pull/1208
https://github.com/AntelopeIO/leap/pull/1204
