### ISSUE TITLE
Smart Contracts Dune Doc - Quality Check

### ISSUE THREAD

**Issue by VEG-Ginna** [eosnetworkfoundation/devrel#251]
Dune Doc: https://docs.eosnetwork.com/docs/latest/smart-contracts/getting-started/dune-guide/

AC:

Check Smart Contracts Dune Doc for the following quality attributes:

Likely to change large portions:
- [x] 2nd person voice
- [x] comprehension (5th grade reading level)
- [ ] ability to machine translate
- [x] grammar (keep it light)
- [x] Make headers first-cap only

Likely only smaller changes
- [x] spelling
- [x] check <title></title> for uniqueness

For things with guide-wide changes, make a separate PR (like title/heading fixes)

**Comment by VEG-Ginna** [comment]
PR #118 docs repo - https://github.com/eosnetworkfoundation/docs/pull/118

**Comment by nsjames** [comment]
I've closed these PRs. Please re-do these in waves as we discussed to reduce the lengthy review requirement on the original writers/reviewers. Thanks!
