### ISSUE TITLE
Smart Contracts Accounts Doc - Quality Check

### ISSUE THREAD

**Issue by VEG-Ginna** [eosnetworkfoundation/devrel#252]
Accounts Doc: https://docs.eosnetwork.com/docs/latest/smart-contracts/getting-started/Accounts

AC:

Check Smart Contracts Accounts Doc for the following quality attributes:

Likely to change large portions:
- [ ] 2nd person voice
- [x] comprehension (5th grade reading level)
- [ ] ability to machine translate
- [x] grammar (keep it light)

Likely only smaller changes
- [ ] spelling
- [ ] check <title></title> for uniqueness
- [x] Make headers first-cap only

For things with guide-wide changes, make a separate PR (like title/heading fixes)

**Comment by VEG-Ginna** [comment]
PR [137](https://github.com/eosnetworkfoundation/docs/pull/137/files)

**Comment by nsjames** [comment]
I've closed these PRs. Please re-do these in waves as we discussed to reduce the lengthy review requirement on the original writers/reviewers. Thanks!
