### ISSUE TITLE
Smart Contracts Tic-tac-toe Game Contract Doc - Quality Check

### ISSUE THREAD

**Issue by VEG-Ginna** [eosnetworkfoundation/devrel#259]
Tic-tac-toe Game Contract Doc: https://docs.eosnetwork.com/docs/latest/smart-contracts/tutorials/tic-tac-toe-game-contract

Check Smart Contracts Tic-tac-toe Game Contract Doc for the following quality attributes:

Likely to change large portions:
- [ ] 2nd person voice
- [ ] comprehension (5th grade reading level)
- [ ] ability to machine translate
- [ ] grammar (keep it light)
- [ ] Make headers first-cap only

Likely only smaller changes
- [ ] spelling
- [ ] check <title></title> for uniqueness

For things with guide-wide changes, make a separate PR (like title/heading fixes)

**Comment by nsjames** [comment]
This guide no longer exists
