### ISSUE TITLE
Create guide to connect an API node to mainnet

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/devrel#282]
Create a guide to help developers raise and connect an API node to the mainnet.

This is not meant to explain:
- History solutions
- Block production

This is meant to explain:
- How to deploy an API node
- Basic hardware requirements
- How to install leap
- How to setup a config.ini
- How to setup peers
- How to start/stop a node
- What blocks.log is
- What a snapshot is and how to replay from one
- What to do if the blocks are "dirty"
- How to set cors to `*` for dapp usage

AC:
- Create table of contents
- Create actual guide

**Comment by nsjames** [comment]
Spike outputs here: https://hackmd.io/@EOSNF/SyMfjCL43
