### ISSUE TITLE
Access to AWS Translation API

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#284]
https://aws.amazon.com/translate/

**Comment by nsjames** [comment]
https://github.com/eosnetworkfoundation/devrel/issues/213

**Comment by kj4ezj** [comment]
An Amazon Web Services (AWS) account has been delivered to the customer with access to AWS translate and associated services. I tried it successfully in the web console using an IAM user test account, but the customer may be doing something more advanced.

**Comment by kj4ezj** [comment]
The customer was able to login and translate things. Yay!
