### ISSUE TITLE
Define create/update/rename process for content using GitHub

### ISSUE THREAD

**Issue by VEG-Ginna** [eosnetworkfoundation/devrel#3]
Document a process to create/update/rename

AC:
- All documents need to provide an example of doing this internally and externally
- Define the process for creating a new document
- Define the process for updating existing documents
- Define the process for renaming a document
- Place process in devrel repo

**Comment by VEG-Ginna** [comment]
Created template for documentation publication process and shared with Eric for his input.
https://docs.google.com/document/d/1SuLSpUt9JyZfdvvwZ-o_yUtuGN66-3s_C--s3iQNlYM/edit#

**Comment by VEG-Ginna** [comment]
Eric provided instructions on how to build a new document repository. https://github.com/eosnetworkfoundation/devdocs/blob/main/docs/How-To-Do-A-Full-Release.md

Still need a procedure on. how to publish new or updated content to the dev portal.

**Comment by ericpassmore** [comment]
Hi, how to publish or update content is on the README. Let me know if updates or clarifications are needed. 
https://github.com/eosnetworkfoundation/devdocs/blob/main/README.md

**Comment by VEG-Ginna** [comment]
thx
