### ISSUE TITLE
Node Operator Guides: Hardware Requirements

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#307]
Finalize this section with the information from this ticket: https://github.com/eosnetworkfoundation/devrel/issues/133

AC:
- Write the content for the doc in the node operators section
- Test on staging
- Deploy to production

**Comment by iamveritas** [comment]
Notes:

Thoughts from Aaron and Ross:
https://t.me/NodeOperatorsRoundtable/2226
https://t.me/NodeOperatorsRoundtable/2229
https://t.me/NodeOperatorsRoundtable/2230
https://t.me/NodeOperatorsRoundtable/2238

WAX requirements
https://t.me/NodeOperatorsRoundtable/2258

**Comment by iamveritas** [comment]
PR in review
https://github.com/eosnetworkfoundation/docs/pull/159
