### ISSUE TITLE
Using Remix to develop Smart Contract & Deploy

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#324]
Topics: 
- Setting up remix with EOS EVM (link to existing guide)
- Writing a basic contract
- Building 
- Deploying
- Verify smart contract
  - Get constructor params (see historical version)
  - [Flattening your contract](https://docs.xdc.community/get-details/smart-contract-details/flattening-smart-contracts/flattening-smart-contracts-with-remix)
- Testing

AC:
- Add to evm/smart-contracts
- **When done, create an identical ticket referencing this one that is for the video tutorial epic**

**Comment by nsjames** [comment]
This work is already done in history: https://github.com/eosnetworkfoundation/docs/commits/f99d57627369234e1620f4c2b09c8932d3a72d7c/docs/50_eos-evm/20_getting_started/50_develop-with-hardhat.md?browsing_rename_history=true&new_path=docs/50_eos-evm/20_smart-contracts/10_configure_tooling/10_remix.md&original_branch=staging

**Comment by iamveritas** [comment]
PR in review
https://github.com/eosnetworkfoundation/docs/pull/167/files

and ticket for video tutorial created
https://github.com/orgs/eosnetworkfoundation/projects/18/views/10?filterQuery=-status%3ADone%2CDiscarded+vertical%3ADocs+-epic%3A%22Technical+Writing%22+&pane=issue&itemId=31437917
