### ISSUE TITLE
Define a "Definition of Done" document

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#44]
AC:
- brainstorm meeting, DevRel team
- Approval by stakeholder (Nathan)
- publish in DevRel repository1

**Comment by VEG-Ginna** [comment]
Definition of done is defined up front before development begins, and applies to all user-stories within a sprint, whereas acceptance criteria are specific to one particular feature and can be decided on much later, just before or even iteratively during development.

DoD tends to cover non-functional and quality factors

example:
- PRD - written product requirement document submitted
- Research with SME is complete
- SME review for accuracy and completeness finalized
- All comments incorporated
- Apply appropriate template
- Edit is complete
- Final review
- Stakeholder signoff
- Publication complete

**Comment by VEG-Ginna** [comment]
Update DevRel repository with folder, and publish to repository
