### ISSUE TITLE
Create a staging URL to review current state of docs before publishing

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/devrel#45]
need to run every day
need a process doc

Note: It's crucial to make sure that `latest` still links to the latest version published on the site, not to the potential new version, if any, which will be tested using the calvary link. @ericpassmore

**Comment by ericpassmore** [comment]
I would like to request separating the work items for _run everyday_ requirements from the staging URL. We plan to discuss the run everyday at next Monday's meeting

**Comment by ericpassmore** [comment]
now working in dev on repo eosnetworkfoundation/devdocs branch preview_version
path _preview_ is the staging URL. It is not available on the nav bar
path _latest_ is the current documentation. It is selectable on the nav bar.

**Comment by ericpassmore** [comment]
Please approve PR https://github.com/eosnetworkfoundation/devdocs/pull/52 
after approval I will merge into main. Video demo shows how this works in production
