### ISSUE TITLE
Add index.md file to cdt how-tos

### ISSUE THREAD

**Issue by lparisc** [eosnetworkfoundation/devrel#52]
The old docs generator used to render directories with no index files - it displayed a view of the directory contents in the UI look and feel. In lack of that feature, we need to add index.md files manually where applicable, or continue to display them using the default web server view (which is better than displaying a 404 at the moment):

File: https://github.com/AntelopeIO/cdt/tree/main/docs/06_how-to-guides/40_multi-index

URL: https://docs.eosnetwork.com/cdt/latest/how-to-guides/multi-index/

URL View (10/5/2022):
![dir-view](https://user-images.githubusercontent.com/1623413/194158563-ede6962f-d308-420e-986c-49fb5b70c9b5.png)

My preference is to add that feature to the docs generator instead of adding manual index.md files. @ericpassmore please let me know whether this is feasible and I'll add the corresponding feature request ticket. If not, I'll continue with this ticket. Thanks

**Comment by lparisc** [comment]
:point_up_2: @ericpassmore when you get a chance

**Comment by ericpassmore** [comment]
This can be accomplished in multiple ways. Possible solutions include
- Write custom React code to build a directory listing where there is none
- Run a command to generate the index file as part of processing the markdown
- Create index markdown files in github repos.

There is a script in `devdocs/scripts` that will generate an index file, fixing the example above. Put the following in install_leap.sh. 

```
./build_index_md.sh -d ../working/AntelopeIO/cdt/markdown_out/06_how-to-guides/40_multi-index/ -n index.md > ../working/AntelopeIO/cdt/markdown_out/06_how-to-guides/40_multi-index/index.md
```
If you want to fix all dirs using this method, need another script to identify the directories without index.md or READMD.md files.
