### ISSUE TITLE
SPIKE - Figure out hierarchy for devrel repo

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#54]
Define structure/hierarchy for DevRel repo, Table of Contents

AC:
- brainstorming session - DevRel team, reach consensus
- List of folders or - ToC in the repository

**Comment by VEG-Ginna** [comment]
Thoughts for ToC:

- Intro to DevRel (hub and docs portal)
- Mission Statement
- Org structure
- Templates
- Dev Roles
- Best Practices (link to Google style guide, Technical Writing for Engineers [Google])
- Doc Portal
- Processes - publication process, review process, writing process (?)
- Community Contribution to Docs (link to templates process, publish process)
- Onboarding - system requirements, mission statement, communication processes, responsibilities, software requirements
