### ISSUE TITLE
Standup DevHub Infrastructure

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/devrel#80]
Details for infra are in this ticket on DevRel: https://github.com/eosnetworkfoundation/devrel/issues/81

> We need a server for a backend component as well as a database

> Minimum DB requirements:
https://docs.couchbase.com/server/current/install/pre-install.html

> The DB will end up being replaced with a service so having them on the same VM saves us future work

## See Also
- [Issue 96](https://github.com/eosnetworkfoundation/devrel/issues/96) - DNS Mapping for learn.eosnetwork.com
  - That ticket is a subset of the work required for this ticket.

**Comment by kj4ezj** [comment]
This work is completed.

An [`m6a.2xlarge`](https://instances.vantage.sh/aws/ec2/m6a.2xlarge) instance was stood up with a 1024 GiB EBS GP3 SSD volume in `us-east-1` in the `devhub` AWS account. The EBS volume is set not to delete on instance termination, so be sure to delete the volume explicitly when tearing down this infrastructure.

The instance is behind an AWS security group with an IP ACL for now. We will need to move this to a modern, zero-trust approach in a subsequent ticket to eliminate the need for management of SSH keys or IP addresses while improving security.

Prices fluctuate, but the current cost estimate of this infrastructure is $330.75/mo (where a month is considered to be 30 days) plus $0.09/GB of network egress.
