### ISSUE TITLE
SPIKE - Define simpler structure for docs sidebar

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#83]
We would like to optimize the docs sidebar by segregating it into developer roles and other high level buckets

- Smart contracts
- Web applications
- Node operation
+ define/discover others

AC:
- Mandatory to have the developer roles as root hierarchy
- Define the sidebar hierarchy
- output is a directory hierarchy which can be just a comment on the PR so that we can capture it 
- mapping to spreadsheet
- Create implementation for mini structure for docs

**Comment by nsjames** [comment]
@nsjames is a mandatory reviewer

**Comment by VEG-Ginna** [comment]
Starting Point - large categories:   - To Be Discussed

- Welcome
- Getting Started
     - Setup System
     - Basics
     - Resources
 - As an App Developer
     - Link to docs
     - Use Cases
-  As a Node Operator
-    - Link to docs
     - Use Cases
- As a Smart Contract Developer
-    - Link to docs
     - Use Cases
- APIs
- How To's - links
- Tutorials - links


- Advanced
     - Protocols
     - Reference

**Comment by VEG-Ginna** [comment]
More thoughts for role use cases

App Developer

- want to set up user access to app
- want to set up admin access to app
- write to database with ledger to user transaction log - available to user
- report user transactions
- access APIs to administration of app
- access APIs to configure app

System contract developer

- add business rules to an app
- add business rules to authentication
- configure authentication
- gather metrics info

Node Operator

- do research for this 

API

- sharpen API definitions - are APIs generated? if so, what do we need to do to add column info, such as limits, description, data type, data format, etc.

**Comment by lparisc** [comment]
To get started with this spike, I'd like to contrast existing doc menu hierarchies from well-known documentation portals, like Ethereum, Solana, etc.

Ethereum

The Ethereum's Dev Doc Portal is available here: https://ethereum.org/en/developers/docs/

The documentation is presented in four different styles according to the developer's preference/learning style:
- Docs (foundational, software stack, advanced topics)
- Tutorials (pool of curated list of tutorials from community)
- Learn by coding (sandboxes for build/deploy, interactive game tutorials, dev bootcamps)
- Set up local env. (tools and frameworks to build locally)

**Comment by lparisc** [comment]
Solana

Solana's Dev Doc Portal available here: https://docs.solana.com/

The docs are presented based on functionality, but also roles (at least two: developers & validators):
- Learn (very light-weight: intro sections, getting started only contains a "wallet" section)
- Architecture (advanced info on protocols and internals)
- CLI (info on client-side app "solana", similar to "cleos")
- Developers (get started, core concepts, clients, writing programs [3rd-party apps], native programs [plugins], local dev [test validator])
- Validators (running a validator, getting started, voting setup, geyser [api nodes])
- More (more like miscellaneous: Terminology, Staking, Integrations, Economics, Proposals. etc.)

**Comment by lparisc** [comment]
A few conclusions after reviewing existing doc portals from other projects (Ethereum, Solana):
- in general, docs from other projects are mainly organized based on functionality, but also according to some roles (in solana at least).
- solana contains two roles (devs and validators) in root hierarchy, but no dev roles separation inside devs.

Bottomline:
- "getting started" is perhaps the most sensical place to organize content based on dev roles. We can start there and expand out if necessary:
  - Smart Contracts
  - Web Applications
  - Node Operation

**Comment by lparisc** [comment]
Potential side-menu:

- Getting Started
  - Smart Contracts
    - Overview
    - Hello World
    - Token Operations
    - Application Binary Interface (ABI)
    - Data Persistence
    - Multi-Indexes
    - Inline Actions
  - Web Applications
    - Overview
    - Setup
      - User access
      - Admin access
      - Configuration
      - Administration
    - Usage
  - Node Operation
    - Overview
    - How to become a Node Operator (or Node Operator Checklist)
    - Node setup Guides:
      - Chain API Node 
      - State History Node 
      - Trace API Node 
      - Peering Node
      - Signing Node

**Comment by nsjames** [comment]
- Getting Started
- Role
- Role
- Role
- Build apps
- EVM

**Comment by lparisc** [comment]
Updated tentative side-menu based on team's feedback on All Hands meeting (1/9/23):

- Getting Started

- Smart Contracts
  - Concepts
    - Overview
    - add current concepts within [smart contract dev](https://docs.eosnetwork.com/docs/latest/getting-started/smart-contract-development/) (token operations, ABI, data persistence, multi indexes, etc.
    - also add CRUD functionality, authentication [getauth], macro usage, etc.
  - Tutorials
    - most items under [smart contract dev](https://docs.eosnetwork.com/docs/latest/getting-started/smart-contract-development/) can be converted to a tutorial format
    - move [tic-tac-toe](https://docs.eosnetwork.com/docs/latest/tutorials/tic-tac-toe-game-smart-contract-single-node) smart contract tutorial here!

- Smart Contracts
  - Overview
  - Concepts
    - add current concepts within [smart contract dev](https://docs.eosnetwork.com/docs/latest/getting-started/smart-contract-development/) (token operations, ABI, data persistence, multi indexes, etc.
    - also add CRUD functionality, authentication [getauth, reqauth], macros usage, etc.
  - Tutorials
    - most items under [smart contract dev](https://docs.eosnetwork.com/docs/latest/getting-started/smart-contract-development/) can be converted to a tutorial format
    - move [tic-tac-toe](https://docs.eosnetwork.com/docs/latest/tutorials/tic-tac-toe-game-smart-contract-single-node) smart contract tutorial here!

- Web Applications
  - Overview
  - Setup (user/admin access, config, etc... define based on wharf setup)
  - Configurations
  - Administration
  - Usage
  - How-to guides (build from eosjs how-tos and make wharf-specific)

- Node Operation
  - Overview
  - Node Operator Checklist (how to become one)
  - Node setup Guides:
    - Chain API Node
    - State History Node
    - Trace API Node
    - Peering Node
    - Signing Node
  - Tools
    - management/configuration
    - monitoring/analytics
  - Security (suggestions to keep nodes secure)
  - Operation
    - Failover
    - Replays/Recovery
    - Performance/Scaling
  - ...add more...

- Build apps (won't this section overlap with *web applications* section? @nsjames)
- 
- EVM

**Comment by lparisc** [comment]
sidebar menu contents finalized. Creating action tickets next.

**Comment by ericpassmore** [comment]
Remove image dependancies https://github.com/eosnetworkfoundation/docsgen/issues/84
