### ISSUE TITLE
Create documentation snapshot for Antelope docs

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#84]
We would like to create a snapshot of the relevant repositories which are needed for generating a static docs site so that we can create a copy of the docs gen for antelope

AC:
- Identify which repos are needed and which tags
- Output a list of the repos and branches into a document or as a comment on this issue
- If no tag exists, create a tag

**Comment by VEG-Ginna** [comment]
Need hash from the current repo where we will start the ENF version for Leap and CDT
Dune - do we need a separate Dune for EOS and Antelope?

**Comment by iamveritas** [comment]
We need the following repos:

1. From Github AntelopeIO Org
- [Leap](https://github.com/AntelopeIO/leap)
- [CDT](https://github.com/AntelopeIO/cdt)
- [DUNE](https://github.com/AntelopeIO/DUNE)
- [Reference Contracts](https://github.com/AntelopeIO/reference-contracts)

2. From Github EOSNetworkFoundation Org, these have to be forked to  Github AntelopeIO Org
- [Docs](https://github.com/eosnetworkfoundation/docs)
- [DevDocs](https://github.com/eosnetworkfoundation/devdocs)

We have to tag each one with `Antelope_docs_v1`, the current main

We need change the devdocs script to replace EOS Developer Documentation -> Antelope Developer Documentation on the landing page and on the.

We need to change the devdocs script to sync with the `Antelope_docs_v1` tag (make it support an input param that specified the tag to pull).

Provide a quick how to generate Antelope docs as an md and place it in the `devdocs`.
