### ISSUE TITLE
Migrate eos docs between antelope to enf

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#85]
We need to create a copy of the docs gen and all require repos for docs site generation to the antelope org

AC:
- Copy over all related repos with the correct tags defined in #84 
- Create a static build locally to validate the validity of the generation on antelope org

**Comment by VEG-Ginna** [comment]
may need to move docs from ENF to Antelope

**Comment by iamveritas** [comment]
see this for the TO DOs for this task
https://github.com/eosnetworkfoundation/devrel/issues/84#issuecomment-1319159688
