### ISSUE TITLE
Proofread "How to Build/Deploy/Maintain the RPC node on EVM"

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/devrel#90]
"1. Nodes: How to Build/Deploy/Maintain the RPC node on EVM
    I think Kanya is working on this part and doing very well"

SMEs:
- Kayan

AC: 
- need link to doc
- provide review comments to Kayan

**Comment by VEG-Ginna** [comment]
**Notes**:  Telegram conversation Nov 10 - https://docs.google.com/document/d/1reJTS4bhghBhJ8te60CHijp4iLFQeK8fXBu3dXNIw00/edit#heading=h.ui19ky1x31lt
